### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by jswigart** [klutch/UnityGifDecoder#2]

**Comment by klutch** [comment]
I hadn't given it a license. I don't mind if other people freely use it or modify it. Do you have a suggestion for a license?

**Comment by klutch** [comment]
Gave it a GPL3 license.

**Comment by jswigart** [comment]
So it's basically not usable in commercial apps?

**Comment by klutch** [comment]
Apparently GPL3 was more restrictive than I thought it was. I've removed the previous commits from the repo where I had given it GPL3, and gave it a BSD license instead. From what I understand (I'm new to licenses), BSD can be used in commercial apps.

**Comment by jswigart** [comment]
Much appreciated!
